-- 0025 — what the embedder needs to be told, written down at intake (#137).
--
-- Orientation is decided long before anybody picks up a mould: which face goes
-- down, which end is proximal, whether the fragment gets bisected. Until now
-- that instruction had nowhere to live. It went into "Sectioning / Cut Notes",
-- which is read at the microtome — one station too late — or into General
-- Notes, where it is buried among everything else about the block.
--
-- Its own column, so it can be asked for at creation and shown to the person
-- doing the embedding.
--
-- Additive, per docs/shared_data_sync.md §1: an older build simply ignores the
-- column and keeps working, and an older image opened by this build gets it
-- from ensureRuntimeSchema(). NOT NULL DEFAULT '' means every existing row is
-- filled in place with the empty string — no row is rewritten, nothing is lost.
ALTER TABLE samples ADD COLUMN embedding_notes TEXT NOT NULL DEFAULT '';
